\input texinfo.tex
@c %**start of header
@setfilename ccstructs.info
@settitle CCStructs
@c %**end of header

@include version.texi
@include macros.texi

@c page
@c ------------------------------------------------------------
@c Values.
@c ------------------------------------------------------------

@set TITLE                      CCStructs

@c To be used as @value{PACKAGE} whenever we need to include the full
@c name of this package.
@set PACKAGE                    CCStructs

@c To be used as @value{PACKAGE} whenever we need to include the
@c nickname of the project: the name that is used to compose the
@c distribution tarball or the web address.
@set PACKAGE_NICKNAME           ccstructs

@c To be used as @value{AUTHOR} whenever we need to include the list of
@c authors of this document.
@set AUTHOR                     Marco Maggi

@c To be used as @value{AUTHOR_EMAIL} whenever we need to include the
@c email of the *single* author of this document.
@set AUTHOR_EMAIL               @email{marco.maggi-ipsu@@poste.it}

@c To be used as @value{COPYRIGHT_YEARS} whenever we need to include the
@c list of copyright years.
@set COPYRIGHT_YEARS            2018

@c ------------------------------------------------------------

@set CCEXCEPTIONS_VERSION       0.8.0
@set CCMEMORY_VERSION           0.2.0
@set CCTESTS_VERSION            0.3.0

@set GITHUB_URL                 @url{https://github.com/marcomaggi/@value{PACKAGE_NICKNAME}}
@set BITBUCKET_URL              @url{https://bitbucket.org/marcomaggi/@value{PACKAGE_NICKNAME}}
@set DOWNLOAD_URL               @url{https://bitbucket.org/marcomaggi/@value{PACKAGE_NICKNAME}/downloads}
@set DOCUMENTATION_URL          @url{https://marcomaggi.github.io/docs/@value{PACKAGE_NICKNAME}.html}

@c page
@c ------------------------------------------------------------
@c Copyright notice.
@c ------------------------------------------------------------

@copying
This document describes version @value{VERSION} of @value{PACKAGE}, a C11 language library
implementing common interface for C structs.

This package supports @posix{} platforms.  This package depends on the packages: CCExceptions, at
least version @value{CCEXCEPTIONS_VERSION}; CCMemory, at least version @value{CCMEMORY_VERSION}.  To
run the test suite: this package depends upon the package CCTests, at least version
@value{CCTESTS_VERSION}.

The package is distributed under the terms of the @gnu{} Lesser General Public License (@lgpl{}).

The latest release can be downloaded from:

@center @value{DOWNLOAD_URL}

@noindent
development takes place at:

@center @value{GITHUB_URL}

@noindent
and as backup at:

@center @value{BITBUCKET_URL}

@noindent
Copyright @copyright{} @value{COPYRIGHT_YEARS} by @value{AUTHOR} @value{AUTHOR_EMAIL}

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the @gnu{}
Free Documentation License, Version 1.3 or any later version published by the Free Software
Foundation; with Invariant Sections being ``@gnu{} Free Documentation License'' and ``@gnu{} General
Public License'', no Front--Cover Texts, and no Back--Cover Texts.  A copy of the license is
included in the section entitled ``@gnu{} Free Documentation License''.
@end quotation
@end copying

@c page
@c ------------------------------------------------------------
@c Headers.
@c ------------------------------------------------------------

@titlepage
@title @value{TITLE}
@subtitle Revision @value{VERSION}
@author @value{AUTHOR} @value{AUTHOR_EMAIL}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ------------------------------------------------------------

@ifinfo
@dircategory Development
@direntry
* ccstructs: (ccstructs).       Common interfaces for C structs.
@end direntry
@end ifinfo

@c ------------------------------------------------------------

@ignore
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp
@end ignore

@c page
@ifnottex
@node Top
@top @value{TITLE}

@insertcopying

@menu
* overview::                    Overview of the package.
* version::                     Version functions.
* memory::                      Memory handling.
* core::                        Core type definitions.
* dtors::                       The @emph{destructors} interface.
* writable::                    The @emph{writable} interface.
* utils::                       Utility definitions.

Appendices

* Package License::             GNU Lesser General Public License.
* Documentation License::       GNU Free Documentation License.
* references::                  Bibliography and references.

Indexes

* concept index::               An entry for each concept.
* function index::              An entry for each function.
* variable index::              An entry for each variable.
* type index::                  An entry for each type.
@end menu
@end ifnottex

@c page
@node overview
@chapter Overview of the package


This document describes version @value{VERSION} of @value{PACKAGE}, a C11 language library
implementing common interfaces for C structs.

This package supports @posix{} platforms.  This package depends on the packages: CCExceptions, at
least version @value{CCEXCEPTIONS_VERSION}; CCMemory, at least version @value{CCMEMORY_VERSION}.  To
run the test suite: this package depends upon the package CCTests, at least version
@value{CCTESTS_VERSION}.

@value{PACKAGE} installs the single header file @file{ccstructs.h}.  All the function names in the
@api{} are prefixed with @code{ccstructs_}; all the preprocessor symbol names are prefixed with
@code{CCSTRUCTS_}; all the type names are prefixed with @code{ccstructs_} and suffixed with
@code{_t}.

@menu
* overview linking::            Linking code with the library.
@end menu

@c page
@node overview linking
@section Linking code with the library


This package installs a data file for @command{pkg-config}, so when searching for the installed
library with the @gnu{} Autotools, we can add the following macro use to @file{configure.ac}:

@example
PKG_CHECK_MODULES([CCSTRUCTS],[ccstructs >= 0.1.0])
@end example

@noindent
which will set the variables @code{CCSTRUCTS_LIBS} and @code{CCSTRUCTS_CFLAGS}.  To avoid
problems with @command{pkg-config}, we need to remember that:

@itemize
@item
The macro file defining @code{PKG_CHECK_MODULES} is installed by the package @code{pkg-config}; such
file usually is in one of the locations:

@center @file{/usr/share/aclocal/pkg.m4}
@center @file{/usr/local/share/aclocal/pkg.m4}

@item
The macro file is located by @command{aclocal}, which in turn is installed by the package @gnu{}
Automake; @command{aclocal} is used by @command{autoreconf}.  We must make sure that
@command{aclocal} finds the installed macro files; for this purpose we can use the environment
variable @env{ACLOCAL_PATH}; under a Bourne shell we can do this with:

@example
export ACLOCAL_PATH=/usr/local/share/aclocal:/usr/share/aclocal
@end example
@end itemize

Alternatively we can use the raw @gnu{} Autoconf macros:

@example
AC_CHECK_LIB([ccstructs],[ccstructs_version_string],,
  [AC_MSG_FAILURE([test for CCStructs library failed])])
AC_CHECK_HEADERS([ccstructs.h],,
  [AC_MSG_FAILURE([test for CCStructs header failed])])
@end example

@c page
@node version
@chapter Version functions


The installed libraries follow version numbering as established by the @gnu{} Autotools.  For an
explanation of interface numbers as managed by @gnu{} Libtool @xref{Libtool versioning, interface,
Libtool's versioning system, libtool, Shared library support for @gnu{}}.


@deftypefun {char const *} ccstructs_version_string (void)
Return a pointer to a statically allocated @asciiz{} string representing
the interface version number.
@end deftypefun


@deftypefun int ccstructs_version_interface_current (void)
Return an integer representing the library interface current number.
@end deftypefun


@deftypefun int ccstructs_version_interface_revision (void)
Return an integer representing the library interface current revision
number.
@end deftypefun


@deftypefun int ccstructs_version_interface_age (void)
Return an integer representing the library interface current age.
@end deftypefun

@c page
@node memory
@chapter Memory handling


@menu
* memory blocks::               Memory blocks.
* memory ascii::                Handling @ascii{} strings.
@end menu

@c page
@node memory blocks
@section Memory blocks


This module offers a set of functions to handle memory blocks; its purpose is to provide a small
data structure (@code{ccstructs_block_t}) which can be used directly as argument to function and
return value from function, instead of the couple: pointer to memory block, block length in bytes.
All the functions are defined in the header @file{ccstructs.h} and declared as @code{__inline__}.


@deftp {Struct Typedef} ccstructs_block_t
The type of memory block; fields description follows:

@table @code
@item size_t len
The number of bytes in the block; can be zero.

@item uint8_t * ptr
Pointer to the memory block or @cnull{}.
@end table

To initialise a block to empty state do this:

@example
ccstructs_block_t     B = @{ .ptr = NULL, .len = 0 @};
@end example

@noindent
or this:

@example
ccstructs_block_t     B;
ccstructs_block_reset(&B);
@end example
@end deftp

@c ------------------------------------------------------------

@subsubheading Memory allocation


@deftypefun ccstructs_block_t ccstructs_block_alloc (ccstructs_memory_allocator_t @var{allocator}, size_t @var{dim})
@deftypefunx ccstructs_block_t ccstructs_block_realloc (ccstructs_memory_allocator_t @var{allocator}, ccstructs_block_t @var{block}, size_t @var{new_dim})
Allocate or reallocate a memory block using the @var{allocator} and
return the resulting block.
@end deftypefun


@deftypefun void ccstructs_block_free (ccstructs_memory_allocator_t @var{allocator}, ccstructs_block_t @var{block})
If the @code{ptr} field of @var{block} is not @cnull{}: free the
referenced memory block using @var{allocator}.
@end deftypefun


@subsubheading Setting

@deftypefun void ccstructs_block_set (ccstructs_block_t * @var{block}, void * @var{ptr}, size_t @var{len})
Set the fields of the block structure.
@end deftypefun


@deftypefun void ccstructs_block_reset (ccstructs_block_t * @var{block})
Reset to zero all the fields of the block.
@end deftypefun


@subsubheading Inspection


@deftypefun bool ccstructs_block_is_null (ccstructs_block_t @var{block})
Return true if the @code{ptr} field of @var{block} is @cnull{}.
@end deftypefun


@subsubheading Memory operations


@deftypefun void ccstructs_block_clean_memory (ccstructs_block_t @var{block})
Reset to zero all the bytes in the memory block.
@end deftypefun


@subsubheading Block operations


@deftypefun void ccstructs_block_shift_x (ccstructs_block_t * @var{block}, ssize_t @var{offset}, size_t @var{dim})
Shift the memory reference in @var{block} by @var{offset} slots each of
@var{dim} bytes.  @var{offset} can be zero, positive or negative.
@end deftypefun


@deftypefun ccstructs_block_t ccstructs_block_shift (ccstructs_block_t @var{block}, ssize_t @var{offset}, size_t @var{dim})
Like @cfunc{ccstructs_block_shift_x}, but produce a new block.
@end deftypefun


@deftypefun ccstructs_block_t ccstructs_block_difference (ccstructs_block_t @var{a}, ccstructs_block_t @var{b})
This function assumes that @var{b} is contiguous to or included in
@var{a}; return a new block @var{c} referencing the first portion of
@var{a} not in @var{b}.

@example
          @var{c}.len             @var{b}.len
  |.........................|.................|

@var{c}.ptr                     @var{b}.ptr
  v                         v
  |-------------------------|---------------------|
  ^
@var{a}.ptr

  |...............................................|
                       @var{a}.len

@end example
@end deftypefun

@c page
@node memory ascii
@section Handling @ascii{} strings


This module offers a set of functions to handle @ascii{} coded, zero
terminated strings; its purpose is to provide a small data structure
(@code{ccstructs_ascii_t}) which can be used directly as argument to function
and return value from function, instead of the couple: pointer to memory
block, block length in bytes.  All the functions are defined in the
header @file{ccstructs.h} and declared as @code{__inline__}.


@deftp {Struct Typedef} ccstructs_ascii_t
The type of zero--terminated @ascii{} strings; fields description
follows:

@table @code
@item size_t len
The number of characters in the block; can be zero; it does @strong{not}
include the terminating null character.

@item char * ptr
Pointer to the memory block or @cnull{}; the last @code{char} must be
zero.
@end table

To initialise an ascii to empty state do this:

@example
ccstructs_ascii_t     A = @{ .ptr = NULL, .len = 0 @};
@end example

@noindent
or this:

@example
ccstructs_ascii_t     A;
ccstructs_ascii_reset(&A);
@end example

@noindent
or this:

@example
ccstructs_ascii_t     A = ccstructs_ascii_empty;
@end example
@end deftp


@deftp {Struct Typedef} ccstructs_ascii_list_t
Holds an array of @code{char *}.  Fields:

@table @code
@item size_t len
the number of strings;
@item char ** ptr
the array of pointers.
@end table
@end deftp


@deftypevar {const ccstructs_ascii_t} ccstructs_ascii_empty
Represent an empty string.  It is a statically allocated structure,
referencing a zero--terminated empty string.
@end deftypevar


@deftypefun void ccstructs_ascii_set (ccstructs_ascii_t * @var{ascii}, void * @var{ptr}, size_t @var{len})
Initialise the fields of a structure.
@end deftypefun


@deftypefun void ccstructs_ascii_reset (ccstructs_ascii_t * @var{ascii})
Reset to zero the fields.
@end deftypefun


@deftypefun ccstructs_ascii_t ccstructs_ascii_const (char * @var{string})
Build and return a structure initialised with @var{string}.  The length
is determined with the standard @cfunc{strlen} function.
@end deftypefun


@deftypefun bool ccstructs_ascii_is_null (ccstructs_ascii_t @var{ascii})
Return true if the pointer field is set to @cnull{}.
@end deftypefun


@deftypefun ccstructs_bool_t ccstructs_ascii_is_terminated (ccstructs_ascii_t @var{ascii})
Return true if the string referenced by @var{ascii} is zero--terminated.
@end deftypefun


@deftypefun void ccstructs_ascii_clean_memory (ccstructs_ascii_t @var{ascii})
Reset the block of memory to zero bytes.
@end deftypefun


@deftypefun void ccstructs_ascii_terminate (ccstructs_ascii_t @var{ascii})
Make sure that the string referenced by @var{ascii} is zero--terminated.
@end deftypefun


@deftypefun ccstructs_block_t ccstructs_block_from_ascii (ccstructs_ascii_t @var{ascii})
Return a block initialised with the fields of an @ascii{} block.
@end deftypefun

@deftypefun ccstructs_ascii_t ccstructs_ascii_from_block (ccstructs_block_t @var{block})
Return an @ascii{} block initialised with the fields of a block.
@end deftypefun


@deftypefun ccstructs_ascii_t ccstructs_ascii_alloc (ccstructs_memory_allocator_t @var{allocator}, size_t @var{dim})
@deftypefunx ccstructs_ascii_t ccstructs_ascii_realloc (ccstructs_memory_allocator_t @var{allocator}, ccstructs_ascii_t @var{ascii}, size_t @var{new_dim})
Allocate or reallocate an @ascii{} block using @var{allocator};
@var{dim} and @var{new_dim} are the number of characters to be stored in
the block, with the @strong{exclusion} of the terminating zero.
@end deftypefun


@deftypefun void ccstructs_ascii_free (ccstructs_memory_allocator_t @var{allocator}, ccstructs_ascii_t @var{ascii})
If the @code{ptr} field of @var{ascii} is not @cnull{}: free the
referenced memory block using @var{allocator}.
@end deftypefun


@c page
@node core
@chapter Core type definitions


@value{PACKAGE} offers an @api{} to handle @struct{} values.  The library cannot reference the
concrete types of @struct{} the client libraries will use, so it just defines a placeholder for
them.


@deftp {Struct Typedef} ccstructs_core_t
Type of @struct{} values used as argument to @value{PACKAGE} functions.  This is just a forward type
declaration: there is no actual declaration of this type.
@end deftp


When using this type we need to explicitly cast a pointer to client @struct{} values to a pointer to
@objtype{ccstruct_core_t}.  For example, when defining a constructor for the @emph{writable}
interface:

@example
ccstructs_writable_I
spiffy_new_iface_writable (spiffy_t * S)
@{
  return ccstructs_new_writable((ccstructs_core_t *)S,
     &spiffy_writable_iface_methods);
@}
@end example

@c page
@node dtors
@chapter The @emph{destructors} interface


The @emph{destructors} interface provides a uniform way to call a @struct{} destructors.

@menu
* dtors api::                   @emph{destructors} interface @api{}.
* dtors sample empty::          Example of @emph{destructors} interface
                                with empty @code{delete} method.
* dtors sample non-empty::      Example of @emph{destructors} interface
                                with empty @code{delete} method.
@end menu

@c page
@node dtors api
@section @emph{destructors} interface @api{}


@deftp {Struct Typedef} ccstructs_dtors_I
Type of the @emph{destructors} interface.  Instances of this type are meant to be handed by value to
function calls.
@end deftp


@deftp {Struct Typedef} ccstructs_dtors_I_methods_t
Type of methods table for the @emph{destructors} interface.  It has the following fields:

@table @code
@item ccstructs_dtors_iface_delete_fun_t * delete
Pointer to function implementing the @code{delete} method.  This method releases the memory
allocated for the @struct{} itself, if needed.

@item ccstructs_dtors_iface_final_fun_t * final
Pointer to function implementing the @code{final} method.  Release all the asynchronous resources
owned by the fields of the @struct{}, if any.  The @struct{} itself is left alone.
@end table
@end deftp


@deftypefn {Function Prototype} void ccstructs_dtors_iface_delete_fun_t (ccstructs_dtors_I @var{I})
Type of functions implementing the @code{delete} method.  This method releases the memory allocated
for the @struct{} itself, if needed; if a @struct{} is allocated on the stack or embedded into an
enclosing @struct{}: this method should do nothing.
@end deftypefn


@deftypefn {Function Prototype} void ccstructs_dtors_iface_final_fun_t (ccstructs_dtors_I @var{I})
Type of functions implementing the @code{final} method.  Release all the asynchronous resources
owned by the fields of the @struct{}, if any.  The @struct{} itself is left alone.
@end deftypefn


@deftypefun ccstructs_dtors_I ccstructs_new_dtors (ccstructs_core_t * @var{S}, ccstructs_dtors_I_methods_t const * @var{M})
Build and return a new @emph{destructors} interface.
@end deftypefun


@deftypefun {ccstructs_core_t const *} ccstructs_dtors_self (ccstructs_dtors_I @var{I})
Return a pointer to the @struct{} to which the interface belongs.
@end deftypefun


@deftypefun void ccstructs_dtors_final (ccstructs_dtors_I @var{I})
Apply the @code{final} method to the @struct{}.  This function is the faster destructor for a
@struct{} allocated on the stack or embedded in an enclosing @struct{}.
@end deftypefun


@deftypefun void ccstructs_dtors_delete (ccstructs_dtors_I @var{I})
Apply the @code{final} method to the @struct{}, then apply the @code{delete} method to the
@struct{}.  This function is always a correct destructor for a @struct{}.
@end deftypefun

@c page
@node dtors sample empty
@section Example of @emph{destructors} interface with empty @code{delete} method


Let's consider a @struct{} with the following definition:

@example
typedef struct one_t    one_t;

struct one_t @{
  void *  pointer;
@};
@end example

@noindent
we assume instances of this type are always allocated on the stack or embedded in an enclosing
@struct{}.  We can implement the @emph{destructor} interface as follows:

@example
static void
one_dtors_method_delete (ccstructs_dtors_I I)
@{
@}

static void
one_dtors_method_final (ccstructs_dtors_I I)
@{
  CCSTRUCTS_PC(one_t, S, ccstructs_dtors_self(I));

  ccmem_free(ccmem_standard_allocator, S->pointer);
@}

static ccstructs_dtors_I_methods_t const one_dtors_iface_methods = @{
  .delete       = one_dtors_method_delete,
  .final        = one_dtors_method_final
@};

ccstructs_dtors_I
one_new_iface_dtors (one_t * S)
@{
  return ccstructs_new_dtors((ccstructs_core_t *)S, &one_dtors_iface_methods);
@}
@end example

@noindent
and we can use the interface as follows:

@example
cce_location_t        L[1];

if (cce_location(L)) @{
  cce_run_catch_handlers_raise(L, upper_L);
@} else @{
  one_t       S = @{
    .pointer  = ccmem_malloc(L, ccmem_standard_allocator, 256)
  @};
  ccstructs_dtors_I   I = one_new_iface_dtors(&S);

  ...
  ccstructs_dtors_delete(I);
  cce_run_body_handlers(L);
@}
@end example

@c page
@node dtors sample non-empty
@section Example of @emph{destructors} interface with empty @code{delete} method


Let's consider a @struct{} with the following definition:

@example
typedef struct two_t    two_t;

struct two_t @{
  void *  pointer;
@};
@end example

@noindent
we assume instances of this type are always allocated on the heap.  We can implement the
@emph{destructor} interface as follows:

@example
static void
two_dtors_method_delete (ccstructs_dtors_I I)
@{
  CCSTRUCTS_PC(two_t, S, ccstructs_dtors_self(I));

  ccmem_free(ccmem_standard_allocator, S);
@}

static void
two_dtors_method_final (ccstructs_dtors_I I)
@{
  CCSTRUCTS_PC(two_t, S, ccstructs_dtors_self(I));

  ccmem_free(ccmem_standard_allocator, S->pointer);
@}

static ccstructs_dtors_I_methods_t const two_dtors_iface_methods = @{
  .delete       = two_dtors_method_delete,
  .final        = two_dtors_method_final
@};

ccstructs_dtors_I
two_new_iface_dtors (two_t * S)
@{
  return ccstructs_new_dtors((ccstructs_core_t *)S, &two_dtors_iface_methods);
@}
@end example

@noindent
and we can use the interface as follows:

@example
cce_location_t        L[1];

if (cce_location(L)) @{
  cce_run_catch_handlers_raise(L, upper_L);
@} else @{
  two_t * S = ccmem_malloc(L, ccmem_standard_allocator, sizeof(two_t));
  S->pointer = ccmem_malloc(L, ccmem_standard_allocator, 256)
  ccstructs_dtors_I   I = two_new_iface_dtors(&S);

  ...
  ccstructs_dtors_delete(I);
  cce_run_body_handlers(L);
@}
@end example

@c page
@node writable
@chapter The @emph{writable} interface


The @emph{writable} interface, represented by the type @objtype{ccstructs_writable_I}, allows us to
write an object to a standard stream of type @objtype{FILE}; it is meant to be used mostly for
inspection and debugging purposes, neither for presentation to the end user of a program, nor for
memorisation on a storage device.


@deftp {Struct Typedef} ccstructs_writable_I
Type of the @emph{writable} interface.  Instances of this type are meant to be handed by value to
function calls.
@end deftp


@deftp {Struct Typedef} ccstructs_writable_I_methods_t
Type of methods table for the @emph{writable} interface.  It has the following fields:

@table @code
@item ccstructs_writable_iface_fwrite_fun_t * fwrite
Pointer to function implementing the @code{fwrite} method.  This method writes a representation of
the object to a standard stream.  If an error occurs: raise an exception by performing a non--local
exit to @var{L}.
@end table
@end deftp


@deftypefn {Function Prototype} void ccstructs_writable_iface_fwrite_fun_t (cce_destination_t @var{L}, FILE * @var{stream}, ccstructs_writable_I @var{I})
Type of functions implementing the @code{fwrite} method.  Write a representation of the object to
the given stream.
@end deftypefn


@deftypefun ccstructs_writable_I ccstructs_new_writable (ccstructs_core_t * @var{S}, ccstructs_writable_I_methods_t const * @var{M})
Interface constructor.  Return a new interface @struct{} given a pointer to the source @struct{} and
a pointer to the interface methods.
@end deftypefun


@deftypefun {ccstructs_core_t const *} ccstructs_writable_self (ccstructs_writable_I @var{I})
Return a pointer to the @struct{} to which the interface belongs.
@end deftypefun


@deftypefun void ccstructs_writable_fwrite (cce_destination_t @var{L}, FILE * @var{stream}, ccstructs_writable_I @var{I})
Apply the method @code{fwrite} to the @struct{} and the given @var{stream}.  If an error occurs:
raise an exception by performing a non--local exit to @var{L}.
@end deftypefun


Let's say we have this @struct{} definition:

@example
typedef struct spiffy_t        spiffy_t;

struct spiffy_t @{
  int   alpha;
  int   beta;
@};
@end example

@noindent
we can implement a @emph{writable} interface as follows:

@smallexample
void
spiffy_fwrite_method (cce_destination_t L, FILE * stream, ccstructs_writable_I I)
@{
  CCSTRUCTS_PC(spiffy_t, S, I.self);
  int   rv;

  errno = 0;
  rv = fprintf(stream, "spiffy_t: alpha=%d, beta=%d", S->alpha, S->beta);
  if (0 > rv) @{
    cce_raise(L, cce_condition_new_errno_clear());
  @}
@}

ccstructs_writable_I_methods_t const spiffy_writable_iface_methods = @{
  .fwrite = spiffy_fwrite_method
@};

ccstructs_writable_I
spiffy_new_iface_writable (spiffy_t * S)
@{
  return ccstructs_new_writable((ccstructs_core_t *)S,
            &spiffy_writable_iface_methods);
@}
@end smallexample

@noindent
then we can use the interface as follows:

@example
cce_location_t        L[1];

if (cce_location(L)) @{
  cce_run_catch_handlers_raise(L, upper_L);
@} else @{
  spiffy_t   S = @{
    .alpha    = 1,
    .beta     = 2
  @};
  ccstructs_writable_I  I = spiffy_new_iface_writable(&S);

  ccstructs_writable_fwrite(L, stderr, I);
  fprintf(stderr, "\n");
  cce_run_body_handlers(L);
@}
@end example

@c page
@node utils
@chapter Utility definitions


@defmac CCSTRUCTS_PC (@var{POINTER_TYPE}, @var{POINTER_NAME}, @var{EXPRESSION})
Preprocessor macro used to define pointer variables initialised with a cast expression.  It expands
to:

@example
POINTER_TYPE * POINTER_NAME = (POINTER_TYPE *) (EXPRESSION)
@end example

For example, the macro use:

@example
CCSTRUCTS_PC(ccstructs_descriptor_test_failure_t, C, _C);
@end example

@noindent
expands into:

@example
ccstructs_descriptor_test_failure_t * C = \
   (ccstructs_descriptor_test_failure_t *) (_C);
@end example
@end defmac


@defmac CCSTRUCTS_UNUSED
Preprocessor macro that is meant to expand into an attribute declaration.  If the symbol
@code{__GNUC__} is defined, the expansion is:

@example
__attribute__((__unused__))
@end example

@noindent
otherwise the expansion is the empty string.
@end defmac

@c page
@c ------------------------------------------------------------
@c Appendices.
@c ------------------------------------------------------------

@include lgpl-3.0.texi
@include fdl-1.3.texi

@c page
@node references
@appendix Bibliography and references


The documentation of @value{PACKAGE} is available online:

@center @value{DOCUMENTATION_URL}

@noindent
the latest release of this package can be downloaded from:

@center @value{DOWNLOAD_URL}

@noindent
development takes place at:

@center @value{GITHUB_URL}

@noindent
and as backup at:

@center @value{BITBUCKET_URL}

@noindent
the package CCExceptions is available at:

@center @url{https://github.com/marcomaggi/ccexceptions/}

@noindent
the package CCMemory is available at:

@center @url{https://github.com/marcomaggi/ccmemory/}

@noindent
the package CCTests is available at:

@center @url{https://github.com/marcomaggi/cctests/}

@c page
@node concept index
@appendix An entry for each concept

@printindex cp

@node function index
@appendix An entry for each function.

@printindex fn

@node variable index
@appendix An entry for each variable.

@printindex vr

@node type index
@appendix An entry for each type.

@printindex tp

@contents
@bye

@c end of file

